apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-toml-1
  namespace: reliability-pp
data:
  traefik.toml: |-
    # my global config
    defaultEntryPoints = ["http"]
    # Log level
    logLevel = "DEBUG"
    # logLevel = "WARNING"
    [traefikLog]
      format   = "json"
    [entryPoints]
      [entryPoints.http]
      address = ":8080"
      [entryPoints.traefik]
      address = ":8081"

    [api]
      entryPoint = "traefik"
      dashboard = true
      debug = true
    [ping]
      entryPoint = "traefik"

    # Metrics definition
    # [metrics]
    #   [metrics.datadog]
    #     address = "dd-agent.kube-system:8125"
    #     pushInterval = "10s"

    [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]

      [metrics.statistics]
        recentErrors = 10

    ################################################################
    # Kubernetes Ingress configuration backend
    ################################################################

    # Enable Kubernetes Ingress configuration backend.
    [kubernetes]

    # Kubernetes server endpoint.
    #
    # Optional for in-cluster configuration, required otherwise.
    # Default: empty
    #
    # endpoint = "http://localhost:8080"

    # Bearer token used for the Kubernetes client configuration.
    #
    # Optional
    # Default: empty
    #
    # token = "my token"

    # Path to the certificate authority file.
    # Used for the Kubernetes client configuration.
    #
    # Optional
    # Default: empty
    #
    # certAuthFilePath = "/etc/ssl/certs/metroscalesio.crt"

    # Array of namespaces to watch.
    #
    # Optional
    # Default: all namespaces (empty array).
    #
    # namespaces = ["default", "production"]
    namespaces = ["reliability-pp"]

    # Ingress label selector to filter Ingress objects that should be processed.
    #
    # Optional
    # Default: empty (process all Ingresses)
    #
    # labelselector = "A and not B"
    # labelselector = "service"

    # Value of `kubernetes.io/ingress.class` annotation that identifies Ingress objects to be processed.
    # If the parameter is non-empty, only Ingresses containing an annotation with the same value are processed.
    # Otherwise, Ingresses missing the annotation, having an empty value, or the value `traefik` are processed.
    #
    # Note : `ingressClass` option must begin with the "traefik" prefix.
    #
    # Optional
    # Default: empty
    #
    ingressClass = "traefik-internal"

    # Disable PassHost Headers.
    #
    # Optional
    # Default: false
    #
    # disablePassHostHeaders = true

    # Enable PassTLSCert Headers.
    #
    # Optional
    # Default: false
    #
    # enablePassTLSCert = true

    # Override default configuration template.
    #
    # Optional
    # Default: <built-in template>
    #
    # filename = "kubernetes.tmpl"  