apiVersion: v1
kind: Service
metadata:
  name: flux
  namespace: reliability-pp
  labels:
    app: flux
    component: flux
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3030
  selector:
    name: flux
  sessionAffinity: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flux
  namespace: reliability-pp
  labels:
    app: flux
    component: flux
spec:
  rules:
  - host: reliability-pp-flux.minikube
    http:
      paths:
      - backend:
          serviceName: flux
          servicePort: 80
status:
  loadBalancer: {}

